- name: install packages
  apt:
    name:
      - git
      - nginx

- name: configure nginx
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-enabled/default

- name: clone project
  git:
    repo: https://github.com/micdm/vavilova15.git
    dest: "{{ www.project_root }}"

- name: start and enable nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
