- name: server
  hosts: server
  roles:
    - role: certbot
      tags:
        - www
    - role: webserver
      tags:
        - www
  vars_prompt:
    - name: group_address
      prompt: Invitation address for WhatsApp
      private: no
