- name: install
  apt:
    name: certbot

- name: create acme directory
  file:
    path: /var/www/acme
    state: directory

- name: create systemd override directory
  file:
    path: /etc/systemd/system/certbot.service.d
    state: directory

- name: create systemd override
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/certbot.service.d/override.conf

- name: reload systemd configuration
  systemd:
    daemon_reload: yes

- name: obtain certificate if not exists
  command:
    cmd: "certbot certonly --standalone -n --agree-tos --email {{ misc.email }} -d {{ www.domain }}"
    creates: "{{ www.cert_root }}"
